# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hguW5R9xE7s8Du7tu4U32r09jXiVISzd
"""

from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

import pandas as pd

df = pd.read_csv(file_name)

df.head()

import matplotlib.pyplot as plt
from datetime import datetime
import pytz

def is_allowed_time():
    ist = pytz.timezone('Asia/Kolkata')
    now_ist = datetime.now(ist)
    return 15 <= now_ist.hour < 17

def filter_jobs(df):
    filtered = df[
        (df['Work Type'] == 'Intern') &
        (df['latitude'] < 10) &
        (~df['Country'].str[0].isin(['A', 'B', 'C', 'D'])) &
        (df['Job Title'].str.len() <= 10) &
        (df['Company Size'] < 50000)
    ]
    return filtered

def plot_preference_worktype(df):
    filtered = filter_jobs(df)

    if filtered.empty:
        print("No data to display for the given filters.")
        return

    count_df = filtered.groupby('Preference').size().reset_index(name='Count')

    plt.figure(figsize=(10,6))
    plt.bar(count_df['Preference'], count_df['Count'], color='teal')
    plt.xlabel('Preference')
    plt.ylabel('Number of Jobs')
    plt.title('Jobs by Preference (Filtered Conditions)')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

if is_allowed_time():
    plot_preference_worktype(df)
else:
    print("⏳ Dashboard available only between 3 PM – 5 PM IST")

